{
      "kind": "Service",
      "apiVersion": "v1",
      "metadata": {
        "name": "hello-node"
      },
      "spec": {
        "ports": [{
          "port": 8080,
          "targetPort": 8080
        }],
        "selector": {
          "app": "example"
        },
        "type": "LoadBalancer"
      }
    }
